train: /home/alexm/PycharmProjects/sales_telegram_bot/backend/item_processing/item_names/train/images
val: /home/alexm/PycharmProjects/sales_telegram_bot/backend/item_processing/item_names/val/images
test: /home/alexm/PycharmProjects/sales_telegram_bot/backend/item_processing/item_names/test/images


names:
  0: item_name
  1: item_volume
  2: item_price
  3: item_sale_prcnt
  4: sale_type
  5: item_member_price
  6: item_price_per_unit
  7: item_initial_price